### ISSUE TITLE
FF4 - Shortcuts and filters issues post-upgrade

### ISSUE THREAD

**Issue by mbabker** [marcobarbosa/minima#24]
On my localhost install for a site I'm working on, I updated from Beta 1 to Beta 2 by just installing the package over the already existing installation (upgrade method basically).  Post upgrade, in Firefox 4, the shortcuts panel displays all items with no effects and the filters bar shows 2 "Show/Hide search & filters" messages, both of which function.  Checked Google Chrome 10.0.648.204 and Safari 5.0.4 and those browsers display correctly.  When I manage to get a good internet connection, I send you a screenshot of what I'm seeing.

**Comment by marcobarbosa** [comment]
Try deleting the language files located in administrator/languages/
- tpl_minima.ini
- mod_myshortcuts.ini

That should fix the double "show/hide search & filters". Curious to see if it fixes the other issue as well.

If it does I'll update the post script to delete those language files with php.

Let me know how it went.

**Comment by mbabker** [comment]
I spent a couple hours messing with it last night.  Deleted the language files from the admin/language folder.  Went and deleted all the files off my file system for the installation then dropped back in the package files for all three items.  None of it actually fixed it, but it was only in Firefox that it was acting up.

Now, it's working right, go figure... LOL.  Maybe something was getting cached that shouldn't of been, or maybe me disabling hardware acceleration did something.  I don't know, but it's finally behaving for me again.

Here's the screenshot from last night:  http://www.flbab.com/images/minima_beta2_postinstall.png

**Comment by marcobarbosa** [comment]
Scary screenshot!

I think what happened to you were 2 things:
1) the menu showing the dropdown is certainly caused by a cache issue or an old css file.
2) the language strings on 'adminitrator/language' files were also causing trouble

1) No idea why this happened. Maybe I should change the file for each release to force non caching.
2) This will be fixed this weekend by adding the "unlink" php function to delete files in the postFlight script

Thanks a lot Michael! Always appreciate your feedback.

**Comment by mbabker** [comment]
You could also add something to the postFlight to clean the cache for the affected extensions, which would at least clear it out on the server side.  I'm pretty sure it ended up being browser caching since it cleared itself up automagically.

**Comment by marcobarbosa** [comment]
And how do I do that? What's the line to clear the cache? 

Need to improve the caching in minima overall (like in the panel)..

_________________________________________Marco Barbosaiam@marcobarbosa.com
http://marcobarbosa.com

sent fromOn Sat, Apr 16, 2011 at 5:30 AM, reply@reply.github.com wrote:
You could also add something to the postFlight to clean the cache for the affected extensions, which would at least clear it out on the server side.  I'm pretty sure it ended up being browser caching since it cleared itself up automagically.

## 

Reply to this email directly or view it on GitHub:
https://github.com/marcobarbosa/minima/issues/24#comment_1011745

**Comment by mbabker** [comment]
JModel::cleanCache($extension) is used throughout the backend to clean a specific cache, it should help here.
