### ISSUE TITLE
Installation white page

### ISSUE THREAD

**Issue by Oceanwatcher** [marcobarbosa/minima#43]
I tried installing Minima on J1.5.24 and J1.7.2 - both gave a white page.

On J1.5.24, it did not show up as installed and that might just be because it was never meant to be installed on J1.5 :-)

On J1.7.2, I had to do the same as on J1.5 - go back to the initial admin page by using the URL field in the browser. I still got a white page, but after flushing the browser cache and reloading, I got it up and it was already set to Minima. Not sure if I like that... I would prefer that it just got installed and I had to go to enable it.

**Comment by marcobarbosa** [comment]
Minima is not compatible with 1.5.x, careful with that (no idea what happens with J! 1.5) :)

If you got a white page that means a PHP error and you have the display error setting turned off. So we can't tell if it's a J! installation error or a minima error.

Minima does set up itself after installation as the default template and that is because we need to fix the modules and positions as well. Otherwise you'd have to do it all yourself (enable 2 modules and 1 template).

**Comment by marcobarbosa** [comment]
@jsanglier also mentioned the auto default setting here:

https://github.com/marcobarbosa/minima/issues/46

Now with two complains that is enough for me to remove it in the next release.

Thanks!
