### ISSUE TITLE
Can't access admin backend/can't log in

### ISSUE THREAD

**Issue by Girts** [marcobarbosa/minima#50]
Hi! Wonderful, amazing admin template! Thanks for a piece of art! :) But!  I have installed on my web site with captcha plugin on the admin login from greatjoomla.com and as a result - login stops after the captcha plugin required action. I can't access my web page administration!!!!!! Can You suggest how to deal with this issue? It's URGENT now! :) (For reference: my web www.latvia-myanmar.org, Great Joomla: http://www.greatjoomla.com/extensions/plugins/core-design-captcha-plugin.html )

P.S. I have solved issue by disabling plugin captcha in the database, but my recommendations is to check that like issues  because of little surprises for people :)

**Comment by marcobarbosa** [comment]
Hello Girts,

So sorry to what happened to you! What a surprise it must have been :)

It's hard if not impossible for me to check for every extension but your problem sounds like a weird implementation of this plugin. Or maybe a JS library conflict, which is also weird since minima uses Mootools.

Let me know if you have any other issues.

**Comment by marcobarbosa** [comment]
I don't know why this is still open.

You're welcome to open it again if this issue remains.
